build_root:
  project_image:
    dockerfile_path: openshift-ci/Dockerfile
resources:
  '*':
    requests:
      cpu: 100m
      memory: 250Mi
tests:
- as: e2e-aws
  steps:
    cluster_profile: aws
    test:
    - as: e2e-run-xtf-tests
      commands: mvn test
      from: src
      resources:
        requests:
          cpu: "2"
          memory: 4Gi
    workflow: ipi-aws
